### ISSUE TITLE
State of masterlist.schema.yaml

### ISSUE THREAD

**Issue by pStyl3** [loot/loot.github.io#105]
https://github.com/loot/loot.github.io/blob/master/masterlist.schema.yaml

https://github.com/loot/loot.github.io/issues/18

Do we still make use of this file in any way? It features data structures we no longer use, such as:

```yaml
          'priority':
            type: int
            range: { min: -2000000000, max: 2000000000 }
```
It also misses other things such as `bash_tags`, `groups` and `prelude`, plus `detail`.

As such I'm questioning if we should remove the file from the repository.
