### ISSUE TITLE
Remove the `sortMasters` message

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot.github.io#115]
```yaml
- &sortMasters
  type: say
  content: 'Plugin''s Masters require sorting. %1%'
  subs: [ '[xEdit - Sort Masters](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#SortingMasterFileLoadOrders)' ]
```

According to the [xEdit docs](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WhenshouldyouuseSortMasters), sorting masters doesn't actually have any affect on the game, it's more a tool for mod authors to sync the order of the masters of a plugin to the order they expect them to be in the load order. There's therefore no reason for us to recommend it to users. I think the only case we do so is if the vanilla plugins in a plugin's masters list isn't sorted as they should be. However, this doesn't actually change anything, it's more of an issue to report to the author of the mod in case building their mod with the vanilla plugins in the wrong order caused them to forward the wrong version of a record if its edited by multiple vanilla plugins. They can then fix any resulting issues & sort it on their end before releasing an update. I don't think we recommend sorting sibling masters as that actually means the user (& we via the masterlists) may need to adjust their load order to match.

As this appears to be the case, we should just remove the message & any special considerations we make for it. This would simplify things a bit as I believe a few plugins have metadata taking master sorting into account (e.g., cleaning data for a plugin pre- & post-sorting). It'll also be one less message to translate. There are currently 63 isntances, with 26 being duplicates in the VR masterlist from the SSE masterlist.
