### ISSUE TITLE
Masterlist Improvements

### ISSUE THREAD

**Issue by pStyl3** [loot/loot.github.io#127]
## Change `&dynamicPatchGroup` to `&dynamicPatchesGroup`

Currently the masterlists for `Starfield`, `Skyrim`, `SkyrimSE`, `Morrowind`, `FalloutNV` and `Enderal` feature the group `&dynamicPatchGroup`, while on the other hand the masterlists for `Oblivion`, `Fallout3` and `Fallout4` feature `&dynamicPatchesGroup`.

Considering that multiple other group names lean towards using words in their plural form (instead of singular form), i.e. `&earlyLoadersGroup`, `&latePatchesGroup`, `&lateChangesGroup`, changing the group name in the six above mentioned masterlists to `&dynamicPatchesGroup` is preferable.

## Add a `description` to `&dynamicPatchesGroup` for all the masterlists

Currently only the `Enderal` masterlist features a description for the `&dynamicPatchesGroup`:
`A group for patches that are dynamically generated by modding tools.`

Therefore add the description in every masterlist, where it is currently missing.

## Reevaluate Mator Smash - `Smashed Patch.esp`

The `prelude` features the following message anchor:
```yaml
  - &onlyUseSmashOrBash
    type: say
    content:
      - lang: en
        text: 'Can be used with a {0} but would require additional work. A Smashed Patch or Bash Patch should be used independently of one another.'
```
While it is - or still should be - true, that only one of the two types of patches should be used at a time, Mator Smash aka `Smashed Patch.esp` is an outdated patching framework. The [original upload](https://www.nexusmods.com/skyrim/mods/90987/) on Nexus has been updated last in May 2018, the [GitHub page](https://github.com/matortheeternal/smash) six years ago, and [Unofficial Mator Smash Updated](https://www.nexusmods.com/skyrimspecialedition/mods/39378/) in October 2021.

That plus the fact, that we **only** use `&onlyUseSmashOrBash` in the `skyrim` and `fallout4` masterlists, I'm inclined to remove the message anchor.

There's also the Sub-Anchor
```yaml
  # &requiresX
  - &requiresBashOrSmash
    <<: *requiresX
    subs: [ '[Wrye Bash](https://www.nexusmods.com/skyrimspecialedition/mods/6837/) or [Smash](https://github.com/matortheeternal/smash/releases/)' ]
    condition: 'not file("Bashed Patch.*\.esp") and not file("Smashed Patch.esp")'
```
.. in the `skyrimse` masterlist, that as can be seen above, calls back to the `&requiresX` message anchor:
```yaml
  - &requiresX
    type: warn
    content:
      - lang: en
        text: 'Requires: {0}'
```
It's only used once, and I think it would be better to only recommend the Bashed Patch here.

## Update Bash Tags within the masterlists

Following my question [on Discord](https://discord.com/channels/473542112974077963/473543945188802580/1366806261248819291), @Infernio updated them:
- https://github.com/loot/skyrimse/pull/3055
- https://github.com/loot/skyrim/pull/849
- https://github.com/loot/fallout4/pull/703
- https://github.com/loot/enderal/pull/58
- The `oblivion`, `fallout3` and `falloutnv` masterlists didn't need any changes
- https://github.com/wrye-bash/wrye-bash/commit/9349a242e352dc79db224f75c766ea68ec23f532
