### ISSUE TITLE
Add `many(<regex>)` function to metadata condition syntax

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot.github.io#40]
"Use only one X plugin" is a message template that pops up a lot in the masterlists, but implementing it requires a compromise in one of two ways:

1. You attach the message to a regex entry, so that it is displayed for all matching plugins. This is simpler and more compact, but the message gets displayed even if only one plugin is used.
2. You attach the message to separate entries for each plugin, with a different regex condition for each entry, checking for the others. This is more complex and verbose, but the message only gets displayed if more than one plugin is present.

To solve this, I propose a `many(<regex>)` condition function, which evaluates to true if there is more than one file match for the regex given, and false otherwise. Example usage:

```
  - name: 'Ushnar''s Re-Skinned Hound.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'regex("Ushnar''s Re-Skinned Houn(d-Default|d-Atronach|d-Dog|d-Wolf)\.esp")'
  - name: 'Ushnar''s Re-Skinned Hound-Default.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'regex("Ushnar''s Re-Skinned Houn(d|d-Atronach|d-Dog|d-Wolf)\.esp")'
  - name: 'Ushnar''s Re-Skinned Hound-Atronach.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'regex("Ushnar''s Re-Skinned Houn(d|d-Default|d-Dog|d-Wolf)\.esp")'
  - name: 'Ushnar''s Re-Skinned Hound-Dog.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'regex("Ushnar''s Re-Skinned Houn(d|d-Default|d-Atronach|d-Wolf)\.esp")'
  - name: 'Ushnar''s Re-Skinned Hound-Wolf.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'regex("Ushnar''s Re-Skinned Houn(d|d-Default|d-Atronach|d-Dog)\.esp")'
```

would become:

```
  - name: 'Ushnar''s Re-Skinned Hound(-(Default|Atronach|Dog|Wolf))?\.esp'
    msg:
      - type: say
        content: 'Only use one Ushnar''s Re-Skinned Hound*.esp'
        condition: 'many(Ushnar''s Re-Skinned Hound(-(Default|Atronach|Dog|Wolf))?\.esp)'
```

@loot/looters: What do you think?
