### ISSUE TITLE
Refactoring masterlist messages

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot.github.io#76]
# Preface
This issue will keep track of message refactoring across all masterlists. It's important to refactor messages to reduce redundancy, keep messages centralized, & give translators less work to do.

# Global Messages
- [x] Consolidate similar global messages across masterlists

## Various `requires*SE` anchors
- [x] Move localized contents to corresponding `globals` nodes
- [x] Remove various `requires*SE` anchors
- [x] Sub in mentions of specific version of *SE & locations to make message generic

## Animation framework (FNIS/Nemesis)
- [x] Sub in location, executable, & names to make message generic
- [x] Add Portuguese translation to TES5 masterlist
- [x] Update older translations in TES5 masterlist
- [x] Add bold to location name & executable
- [x] Tweak grammar of message
- [x] Convert to anchor

## {F4,SK}SE Required Scripts
- [x] Sub in mentions of specific {F4,SK}SE & locations to make message generic
- [x] Add message to TES5 masterlist
- [x] Add bold to Japanese translation to match

## NVAC
- [x] Sub in mentions of specific *SE & game to make message generic

## Dynamically Created Plugins
- [x] Reevaluate message (remove or repurpose for more plugins?) - removed in loot/skyrim#615

## Anchors
- [x] Reevaluate anchors with few localizations or that are redundant
- [x] Replace `semiCompatible` with `patchUnavailable`
- ~~Reevaluate `onlyUseSmashOrBash` (could be replaced with `useOnlyOneX`)~~

# Masterlist-specific
## TES4 Masterlist
- [x] loot/oblivion#232
- [x] loot/oblivion#311

## TES5 Masterlist
- [x] Replace `fixedInOfficialPatchX` with various `alreadyInOrFixedByX` anchors
- [x] Replace `fixedPluginOutSub` & `fixedPluginPreCK` with `obsolete`
- [x] Replace `patchRequiem3rdParty` with `patch3rdParty`
- [x] Replace `installOriginalResources` with new `requiresResources` (see https://github.com/loot/oblivion/issues/232#issuecomment-803494121)
- [x] loot/skyrim#452

## SSE Masterlist
- [x] loot/skyrimse#2587

## FO3 Masterlist
- [x] Reevaluate and either refactor or remove unaliased messages

## FNV Masterlist
- [x] Replace `incMaxLevelMods` with `useOnlyOneX`
- [x] Replace `incWeatherImageSpace` with incompatibilities for a few weather mods
- [x] loot/falloutnv#274

## FO4 Masterlist
- [x] Replace `alreadyInFO4` with `alreadyInOrFixedByX`
- [x] Replace `dlcVersion` with `useVersion`
- [x] Replace `incWithPatchVersionX` with an incompatibility
- [x] Replace `insteadSKEPatch` with an incompatibility
- [x] loot/fallout4#502

## Post-reevaluation clean-up
- [ ] Tweak remaining unaliased messages for easier translation
  - [ ] Reword messages to make them clearer, shorter, more standardized, etc. as appropriate
  - [ ] Replace untranslatable phrases (e.g., filenames, "brand" names, links, form IDs, things that can't/shouldn't be translated)

**Comment by sibir-ine** [comment]
@MacSplody @pStyl3 For `&incWithPatchVersionX`, maybe we can replace it by using a combination of an `inc` `plugin` key & a `display` `file` key?

`&incWithPatchVersionX` is as follows:
```yaml
  - &incWithPatchVersionX
    type: error
    content: 'Incompatible with %1% or greater.'
```

& is currently only substituted with `Fallout 4 Patch 1.5.157.0`.

However, we could use `inc` & `display` keys like so:
```yaml
    inc:
      - name: '../Fallout4.exe'
        display: 'Fallout 4 1.5.157.0+'
        condition: 'version("../Fallout4.exe", "1.5.157.0", >=)'
```

to display a message like:
```
This plugin is incompatible with "Fallout 4 1.5.157.0+", but both files are present.
```

Do you guys think this message would convey that the plugin is incompatible with Fallout 4 version 1.5.157.0 & greater well enough? That way, we can also get around having an untranslated "or greater" if we just substituted that into the `display` key.

**Comment by MacSplody** [comment]
Yeah, it might be okay, the only odd part might be the ", but both files are present.".

**Comment by sibir-ine** [comment]
> 
> 
> Yeah, it might be okay, the only odd part might be the ", but both files are present.".

Yeah, @Ortham mentioned rewording that part in #55. Something like this might be all the more reason to reword it.

**Comment by sibir-ine** [comment]
@MacSplody @pStyl3 For `&incompatibleWithWeatherMods` (TES4) & `&incWeatherImageSpace` (FNV), should we merge these & keep the new alias? Or should we replace them with incompatibilities for a couple of popular weather mods for each mod using them? Combined, they're both only used 11 times (6 in TES4, 5 in FNV). Considering we don't provide blanket statements on incompatibilities anywhere else, I prefer the latter. We can also add `&compatNotes` if any of the mods in question have any.

**Comment by MacSplody** [comment]
> Or should we replace them with incompatibilities for a couple of popular weather mods for each mod using them?

Replacing them with an incompatible list would work.
People do have a habit of using these types of mods together despite being told.
&compatIssuesWithX and &compatNotes would be fine as well,
But it depends on them having compatibility notes we can link.

**Comment by sibir-ine** [comment]
@Ortham @MacSplody @pStyl3 Considering that the `file` structure has a `display` key that an `inc` key can utilize to print things other than file names, I think we probably should reword the incompatibility message. I think it'd be enough to just remove the word "files" (i.e. `This plugin is incompatible with X, but both are present.`), but it'd be good to look at some other ideas & consider any edge cases we can think of before anything is set in stone.

**Comment by sibir-ine** [comment]
@MacSplody @pStyl3 What do you guys think about the global "Dynamically Created Plugin" message in the SLE masterlist?

Here it is for reference:
```yaml
  - type: say
    content: 'A dynamically created plugin is installed. Please refer to the author''s notes for more information on determining the best load order.'
    condition: 'file("ASIS(-Dependency)?\.esp") or file("Automatic (Spells|Variations|Variants)\.esp")'
```

We already have load rules for the mods it references (a few of which are outdated & have been superseded IIRC), so maybe we don't need it? Though, we could repurpose it to check for more dynamic patches instead.

**Comment by pStyl3** [comment]
@sibir-ine Since the "Dynamically Created Plugin" message is only to be found within the SLE masterlist and is also pretty generic, and we already have late loading groups assigned for them, I wouldn't mind removing it. These seem to be the plugins that will display the message:
```yaml
  - name: 'ASIS.esp'
    group: *latePatchGroup

  - name: 'ASIS-Dependency.esp'
    group: *asisGroup

  - name: 'Automatic Spells.esp'
    group: *latePatchGroup

  - name: 'Automatic Variations.esp'
    group: *latePatchGroup

  - name: 'Automatic Variants.esp'
    group: *latePatchGroup
```
[ASIS](https://www.nexusmods.com/skyrim/mods/18436)
[Automatic Spells](https://www.nexusmods.com/skyrim/mods/8853)
[Automatic Variants](https://www.nexusmods.com/skyrim/mods/21377)
