### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot.github.io#77]
Opening this to broadly keep track of localization across all of the masterlists & the program itself. loot/skyrimse#646 & loot/loot#1437 fall under this.

@pStyl3 has created a spreadsheet that comprehensively keeps track of localization for the masterlists & is also a tool for translators to easily access all aliased/global masterlist messages & translations in one centralized, up-to-date document. They can also easily add a translation to the spreadsheet, & we can then add the translations so they don't have to worry about making as many as 8 pull requests across all of the masterlists. The latest version of the spreadsheet can be downloaded in the dedicated translations channel of the [Discord server](https://loot.github.io/discord/) or provided by request here or at a localization issue for a specific masterlist.

Instead, we can discuss localization & provide assistance to translators for the program or any masterlist as well as keep track of localization for the program in this issue.

Comprehensive instructions for localizing the program for your language are available in [this article](https://github.com/loot/loot/blob/master/CONTRIBUTING.md#translating-loot). If you're not comfortable with making a pull request, we can provide the relevant files or strings & add your translations for you.

These are the languages LOOT currently supports & the degree to which their program localizations need to be updated:
- [x] `bg` Bulgarian 🏆 
- [ ] `cs` Czech - **9** strings need translation
- [ ] `da` Danish - **19** strings need translation
- [x] `de` German 🏆 
- [ ] `es` Spanish - **152** strings need translation (in DIRE need of an update)
- [ ] `fi` Finnish - **147** strings need translation (in DIRE need of an update)
- [ ] `fr` French - **53** strings need translation
- [x] `ja` Japanese 🏆 
- [ ] `ko` Korean - **66** strings need translation
- [ ] `pl` Polish - **148** strings need translation (in DIRE need of an update)
- [x] `pt_BR` Portuguese (Brazilian) 🏆 
- [x] `pt_PT` Portuguese 🏆 
- [x] `ru` Russian 🏆 
- [ ] `sv` Swedish - **53** strings need translation
- [ ] `zh_CN` Chinese (Simplified) - **26** strings need translation

NOTE: some languages (e.g. Bulgarian & Portuguese) were added recently & aren't included in the latest version of LOOT (0.16.0) yet.

If your language isn't listed, you can always add your language by following the instructions in the article linked above. Please, feel free to double-check the localization for your language even if it's complete.

**Comment by sibir-ine** [comment]
@ThePotatoChronicler Would you be interested in updating the Czech localization as well as localizing the masterlists?

@Freso Would you be interested in doing the same for Danish?

@Sharlikran Would you be interested in doing the same for Spanish?

@3ventic Would you be interested in doing the same for Finnish?

@cpasmoi Would you be interested in doing the same for French?

@steamb23 & @sean-kang Would you two be interested in doing the same for Korean?

@Trollmen & @yoosk Would you two be interested in doing the same for Polish?

@Lakrits, @simoneddeland, & @ddbb07 Would you three be interested in doing the same for Swedish?

**Comment by sibir-ine** [comment]
@ironmagician Would you be interested in updating the Portuguese localization for the masterlists?

@TokcDK Would you be interested in doing the same for Russian?

**Comment by sibir-ine** [comment]
@kuroko137 & @tktk11 Would you two be interested in doing the same for Japanese?

**Comment by ironmagician** [comment]
> @ironmagician Would you be interested in updating the Portuguese localization for the masterlists?

Sure, I downloaded the spreadsheet. Should be done before the next weekend.

**Comment by sibir-ine** [comment]
> Sure, I downloaded the spreadsheet. Should be done before the next weekend.

@ironmagician Thank you so much! Just FYI, I added instructions on how to use the spreadsheet in the issue description. I'll quote it here as well:

>To enter a translation for a message into the spreadsheet, go to the page for that specific message (as linked in the "Overview" & "StringsByLanguage" sheets) & enter your translation for your language code there (a key is available in the "Master" sheet). If, after pressing `Enter` or clicking away from the cell with your new translation, the cell containing the code for your language turns orange in that sheet & "StringsByLanguage", you have entered it in correctly (assuming you actually changed the translation). We will then easily be able to tell what you have changed. **Note**: you shouldn't enter translations into "StringsByLanguage".

**Comment by sibir-ine** [comment]
@ironmagician The template file was recently updated (in loot/loot@185db1726b453957885dcf16811d0b261a5d413c), so there are 6 new/updated strings that need translating for the program. Could you please update these as well?

@RacerBG Could you please do the same for Bulgarian?

**Comment by RacerBG** [comment]
> 
> 
> @ironmagician The template file was recently updated (in [loot/loot@185db17](https://github.com/loot/loot/commit/185db1726b453957885dcf16811d0b261a5d413c)), so there are 6 new/updated strings that need translating for the program. Could you please update these as well?
> 
> @RacerBG Could you please do the same for Bulgarian?

No problems, I will do it tomorrow though. :smiley:

**Comment by sibir-ine** [comment]
> No problems, I will do it tomorrow though. 😃

No problem at all, take as much time as you need!

**Comment by sibir-ine** [comment]
@ironmagician @RacerBG I've added this message to the masterlist:

`Requires resources (e.g. meshes, textures; not plugins) from %1%.`

Can you guys please provide translations for it as well when you have the chance?

**Comment by RacerBG** [comment]
@sibir-ine This project is getting quite active and by the way, thanks to LOOT yesterday I discovered a patch which was missing in my load order for Skyrim SE. Excellent work, everyone!

"Изисква ресурси (триизмерни модели и текстури, без приставки) от %1%."

**Comment by sibir-ine** [comment]
@ironmagician I'm assuming you downloaded the spreadsheet from Discord, so I just want to let you know that we added a **Translator** role in case you want to register for it in the **role-registration** channel. That way, we can notify you when we need translations more easily. Also, we may add a bot soon that will allow you to add or remove the role whenever you want via a command.

**Comment by sibir-ine** [comment]
@RacerBG Can you please translate this message when you get the chance?

`This plugin is a modding resource and should not be used in-game.`

**Comment by RacerBG** [comment]
> @RacerBG Can you please translate this message when you get the chance?
> 
> `This plugin is a modding resource and should not be used in-game.`

@sibir-ine Of course! I saw it earlier in a commit and I though that this is coming. :smile: 

"Тази приставка е ресурс за модифициране и не трябва да се използва по време на игра."

**Comment by sibir-ine** [comment]
> I saw it earlier in a commit and I though that this is coming.

Lol yup, thanks for the translation!

**Comment by sibir-ine** [comment]
@C0rn3j I believe you discussed this in the Discord a while ago, but would you be interested in updating LOOT's Czech localization?

**Comment by RacerBG** [comment]
@sibir-ine This one?

```
'%1% patcher script available here: %2%'

''Скриптът за кръпки %1% е наличен от: %2%''
```

**Comment by sibir-ine** [comment]
@RacerBG Thanks!

**Comment by sibir-ine** [comment]
@RacerBG 2 strings in LOOT got updated & a (not really) new masterlist message got added recently, so can you please translate them when you get the chance?

The message: `If you add, remove, or update plugins that alter WRLD/CELL records, remember to update this module with **xLODGen**.`

**Comment by RacerBG** [comment]
> @RacerBG 2 strings in LOOT got updated & a (not really) new masterlist message got added recently, so can you please translate them when you get the chance?
> 
> The message: `If you add, remove, or update plugins that alter WRLD/CELL records, remember to update this module with **xLODGen**.`

Here you go:

`Ако добавите, премахнете или обновите приставки, които променят записите WRLD и CELL, трябва да обновите този модул с **xLODGen**.`

**Comment by sibir-ine** [comment]
@RacerBG Awesome, thanks!

**Comment by RacerBG** [comment]
@sibir-ine  Actually, I found 2 strings which are currently missing Bulgarian translation (due to the recent changes in the Oblivion masterlist). If there are more, please, let me know as always. :smiley: 

```
'%1% version.'

'Версия %1%.'

'Language: %1%'

'Език: %1%'
```

**Comment by sibir-ine** [comment]
> Actually, I found 2 strings which are currently missing Bulgarian translation (due to the recent changes in the Oblivion masterlist).

@RacerBG Sorry about that, `%1% version.` got replaced with `Language: %1%`, so Bulgarian was just missing the one. Thanks!

**Comment by sibir-ine** [comment]
@RacerBG When you get the chance, can you please translate the following?

```yaml
  - &moveXFromYToZ
    type: say
    content:
      - lang: en
        text: 'Move %1% from %2% to %3%.'
```

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG When you get the chance, can you please translate the following?
> 
> ```yaml
>   - &moveXFromYToZ
>     type: say
>     content:
>       - lang: en
>         text: 'Move %1% from %2% to %3%.'
> ```

@sibir-ine Always! :smile: 

`"Преместете %1 от %2 в %3."`

**Comment by sibir-ine** [comment]
Perfect, thanks!

**Comment by pStyl3** [comment]
@Steamb23 and @silentdark
This is our old message anchor for our masterlist message `wildEdits`:
```yaml
  - &wildEdits
    type: warn
    content:
      - lang: en
        text: 'This plugin contains wild edits beyond ITM and UDR records and deleted navmeshes and may require additional manual cleaning to not interfere with other mods. %1%'
      - lang: ko
        text: '이 플러그인은 ITM 및 UDR 레코드 이외의 잘못된 편집이 포함되어 있으며, Navmesh가 삭제되어 있습니다. 다른 모드를 방해하지 않도록 추가적인 수동 청소가 필요할 수 있습니다. %1%'
      - lang: zh_CN
        text: '这个插件包含随意编辑的ITM和UDR记录以及已删除的navmeshes，可能需要额外的手动清理，以免干扰其他mod。%1%'
```
We shortened the message a short while ago, so
`This plugin contains wild edits beyond ITM and UDR records and deleted navmeshes and may require additional manual cleaning to not interfere with other mods. %1%`

became
`This plugin contains [wild edits](link) and may require additional manual cleaning to not interfere with other mods. %1%`

where the `link` would be
`https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits`

So the new complete English sentence would become:
`This plugin contains [wild edits](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) and may require additional manual cleaning to not interfere with other mods. %1%`

That means, that all the different translations need to be shortened (and have the link added) as well, so the
`beyond ITM and UDR records and deleted navmeshes` part needs to go.

Could you please have a look and shorten the Korean and Chinese translations?

**Comment by steamb23** [comment]
The Korean translation of the text is as follows: 
> 이 플러그인에는 [잘못된 편집(wild edits)](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits)이 포함되어 있으며 다른 모드와 간섭되지 않도록 추가적인 수동 청소가 필요할 수 있습니다. %1%

'잘못된 편집(wild edits)' left the original text for Koreans who refer to English documents to study modding.
But there are links, so it might be unnecessary. If so, please delete the text in parentheses.

**Comment by pStyl3** [comment]
> '잘못된 편집(wild edits)' left the original text for Koreans who refer to English documents to study modding.
> But there are links, so it might be unnecessary. If so, please delete the text in parentheses.

Since the linked website is pointing to a section called "Wild Edits", I think we can remove the `(wild edits)` from the message. 
Thanks!

**Comment by pStyl3** [comment]
[Reference Post](https://github.com/loot/loot.github.io/issues/77#issuecomment-877578049)

Current implementation of `wildEdits`:
```yaml
  - &wildEdits
    type: warn
    content:
      - lang: en
        text: 'This plugin contains wild edits beyond ITM and UDR records and deleted navmeshes and may require additional manual cleaning to not interfere with other mods. %1%'
      - lang: bg
        text: 'Тази приставка съдържа диви редакции отвъд ITM и UDR записите, както и изтрити navmesh-ове, и може да изисква допълнително ръчно почистване. %1%'
      - lang: da
        text: 'Dette plugin indeholder ukontrollerede redigeringer udover ITM- og UDR-poster og slettede navmesher og kan behøve yderligere manuel oprydning for ikke at forstyrre andre mods. %1%'
      - lang: de
        text: 'Dieses Plugin enthält wilde Modifikationen weit über ITM-, und UDR Einträge und entfernte Navmeshes hinaus und benötigt vermutlich mehr manuelle Säuberung um andere Mods nicht zu beeinträchtigen. %1%'
      - lang: es
        text: 'Este plugin contiene ediciones no intencionadas más allá de los registros asociados a ITM, UDR, así como navmeshes eliminadas y probablemente requiera de una limpieza manual adicional para que no interfiera con otros mods. %1%'
      - lang: fi
        text: 'Tämä liitännäinen sisältää villejä muokkauksia ITM- ja UDR-tietueiden sekä poistettujen navmeshien lisäksi. Manuaalinen lisäpuhdistaminen voi olla tarpeen yhteensopivuuden takaamiseksi. %1%'
      - lang: it
        text: 'Questo plugin contiene pesanti modifiche tra i record ITM e UDR, navmesh cancellate e potrebbe richiedere una pulizia manuale aggiuntiva, in modo da non interferire con altre mod. %1%'
      - lang: ja
        text: 'このプラグインにはITMおよびUDRレコード以外の誤った編集(Wild Edit)が含まれており、navmeshが削除されています。他のmodと干渉しないように、追加の手動クリーニングが必要になる場合があります。%1%'
      - lang: ko
        text: '이 플러그인은 ITM 및 UDR 레코드 이외의 잘못된 편집이 포함되어 있으며, Navmesh가 삭제되어 있습니다. 다른 모드를 방해하지 않도록 추가적인 수동 청소가 필요할 수 있습니다. %1%'
      - lang: pl
        text: 'Ta wtyczka zawiera dzikie edycje (Wild Edit) poza rekordami ITM i UDR oraz usunięte siatki nawigacyjne i może wymagać dodatkowego ręcznego czyszczenia aby nie kolidować z innymi modami. %1%'
      - lang: pt_BR
        text: 'Este plugin contém edições não-intencionais (Wild Edits) além dos registros ITM e UDR e Navmeshes deletadas e pode requerer limpeza manual adicional para que não interfira com outros mods. %1%'
      - lang: pt_PT
        text: 'Este plugin contém edições selvagens (Wild Edits) para além dos registros ITM e UDR, e Navmeshes apagadas. Pode requerer limpeza manual adicional de forma a não interferir com outros mods. %1%'
      - lang: ru
        text: 'Плагин содержит дикие правки, кроме ITM, UDR записей и удаленных навмешей и может потребовать дополнительной ручной чистки, чтобы не кофликтовать с другими модами. %1%'
      - lang: sv
        text: 'Denna plugin innehåller vilda föränringar utanför ITM och UDR-records samt borttagna navmeshes och kan kräva ytterligare manuell rensning för att inte störa andra moddar. %1%'
      - lang: uk_UA
        text: 'Плагін містить дикі правки, крім ITM, UDR записів та видалених навмешів і може вимагати додаткової ручної чистки, щоб не конфліктувати з іншими модами. %1%'
      - lang: zh_CN
        text: '这个插件包含随意编辑的ITM和UDR记录以及已删除的navmeshes，可能需要额外的手动清理，以免干扰其他mod。%1%'
    subs: [ '' ]
```

New implementation:
```yaml
  - &wildEdits
    type: warn
    content:
      - lang: en
        text: 'This plugin contains [wild edits](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) and may require additional manual cleaning to not interfere with other mods. %1%'
      - lang: bg
        text: 'Тази приставка съдържа [диви редакции](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) и може да изисква допълнително ръчно почистване. %1%'
      - lang: da
        text: 'Dette plugin indeholder [ukontrollerede redigeringer](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) og kan behøve yderligere manuel oprydning for ikke at forstyrre andre mods. %1%'
      - lang: de
        text: 'Dieses Plugin enthält [wilde Modifikationen](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) und benötigt vermutlich zusätzliche manuelle Säuberung um andere Mods nicht zu beeinträchtigen. %1%'
      - lang: es
        text: 'Este plugin contiene [ediciones no intencionadas](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) y probablemente requiera de una limpieza manual adicional para que no interfiera con otros mods. %1%'
      - lang: fi
        text: 'Tämä liitännäinen sisältää [villejä muokkauksia](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits). Manuaalinen lisäpuhdistaminen voi olla tarpeen yhteensopivuuden takaamiseksi. %1%'
      - lang: it
        text: 'Questo plugin contiene [pesanti modifiche](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) e potrebbe richiedere una pulizia manuale aggiuntiva, in modo da non interferire con altre mod. %1%'
      - lang: ja
        text: 'このプラグインには[Wild Edit](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) が含まれており、他の改造と干渉を防ぐためには追加の手動クリーニングが必要な場合があります。%1%'
      - lang: ko
        text: '이 플러그인에는 [잘못된 편집](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits)이 포함되어 있으며 다른 모드와 간섭되지 않도록 추가적인 수동 청소가 필요할 수 있습니다. %1%'
      - lang: pl
        text: 'Ta wtyczka zawiera [dzikie edycje](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) i może wymagać dodatkowego ręcznego czyszczenia aby nie kolidować z innymi modami. %1%'
      - lang: pt_BR
        text: 'Este plugin contém [edições não-intencionais](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) e pode requerer limpeza manual adicional para que não interfira com outros mods. %1%'
      - lang: pt_PT
        text: 'Este plugin contém [edições selvagens](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits). Pode requerer limpeza manual adicional de forma a não interferir com outros mods. %1%'
      - lang: ru
        text: 'Плагин содержит [дикие правки](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) и может потребовать дополнительной ручной чистки, чтобы не кофликтовать с другими модами. %1%'
      - lang: sv
        text: 'Denna plugin innehåller [vilda föränringar](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) och kan kräva ytterligare manuell rensning för att inte störa andra moddar. %1%'
      - lang: uk_UA
        text: 'Плагін містить [дикі правки](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#WildEdits) та може вимагати додаткової ручної чистки, щоб не конфліктувати з іншими модами. %1%'
      - lang: zh_CN
        text: '这个插件包含随意编辑的ITM和UDR记录以及已删除的navmeshes，可能需要额外的手动清理，以免干扰其他mod。%1%'
    subs: [ '' ]
```
I'd like to implement this change in the coming days.
`bg` translation by @RacerBG 
`de` translation by myself
`es` translation by @Allen1351
`it` translation by Griam
`ja` translation by Menchi
`ko` translation by @steamb23 
`ru` translation by @IllusiveMan196
`uk_UA` translation by @IllusiveMan196

The `da`, `fi`, `pl`, `pt_BR`, `pt_PT` and `sv` translation were created using the original translations for `wildEdits` and using [DeepL](https://www.deepl.com/translator) to identify which parts of the original translations needed to be removed. The result should be alright, but of course can be adjusted later if needed.

@3ventic 
Would you be able to doublecheck the shortened Finnish translation?

@ironmagician 
Would you be able to doublecheck the shortened Portuguese translation?

The only missing translation that hasn't been shortened until now is the Chinese (Simplified) translation.
Could you take a look @silentdark ?
